config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get 'about' => 'welcome#about'

  get 'contact' => 'welcome#contact'

  get 'method_name' => 'welcome#method_name'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@homaland = "Italy"
  	@wishlist = ["Ireland", "Israel", "New Zealand"]
  	@images = ["ireland.jpeg", "israel.jpg", "new-zealand.jpg"]
  end

  def about
  	@color = params[:color]
  	@shoe_size = params[:shoe_size]
  	@background = params[:color]
  end

  def contact
  end
  def method_name  	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap 101 Template</title>
  	<!-- Latest compiled and minified CSS -->
	<%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" %>
	<!-- Latest compiled and minified JavaScript -->
	<%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js" %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
	<nav class="navbar navbar-default">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <%= link_to "Travel", root_path, class: "navbar-brand" %>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
	        <li class="active"></a><%= link_to "About", about_path%></li>
	        <li class="active"></a><%= link_to "Contact", contact_path%></li>
	        <li class="active"></a><%= link_to "Method_Name", method_name_path%></li>
	      </ul>
	      <!-- <form class="navbar-form navbar-left" role="search">
	        <div class="form-group">
	          <input type="text" class="form-control" placeholder="Search">
	        </div>
	        <button type="submit" class="btn btn-default">Submit</button>
	      </form> -->
	      <ul class="nav navbar-nav navbar-right">
	        <li><a href="#">Link</a></li>
	     <!--    <li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
	          <ul class="dropdown-menu" role="menu">
	            <li><a href="#">Action</a></li>
	            <li><a href="#">Another action</a></li>
	            <li><a href="#">Something else here</a></li>
	            <li class="divider"></li>
	            <li><a href="#">Separated link</a></li>
	          </ul>
	        </li> -->
	      </ul>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>
<%= yield %>
</div>

</body>
</html>

app/views/welcome/about.html.erb
<style>
	body {
		background: <%= @color %>;
	}
</style>

<h1>Here's the about page.</h1>
<p>About stuff...</p>
<p>The page is now <%= @color %>.</p>
<p>My shoe size is <%= @shoe_size %>.</p>
<% if @shoe_size.to_i > 12 %>
	<h3>HUGE FEET!!!!</h3>
<% end %>

<%= link_to "Blue", {controller: "welcome", action: "about", color: "Blue"}, class: "btn btn-primary" %>
<%= link_to "Red", {controller: "welcome", action: "about", color: "Red"}, class: "btn btn-danger" %>

app/views/welcome/contact.html.erb
<h1>Contact Us</h1>
<p>email</p>

app/views/welcome/index.html.erb
<h1>Welcome</h1>
<p>This is a web page.</p>
<p></p>

<ul>
<% @wishlist.each do | country | %>
	<li><%= country %></li>
<% end %>
</ul>

<%= image_tag "ireland.jpeg", alt: "Ireland", width: "300"%>
<%= image_tag "israel.jpg", alt: "Israel",  width: "300"%>
<%= image_tag "new-zealand.jpg", alt: "New Zealand",  width: "300"%>


<% @images.each do | image | %>
	<%= image_tag image, class: "img-responsive" , height: "230" %>
<% end %>

app/views/welcome/method_name.html.erb
<h1>Method Name</h1>
<h2>Kangaroo</h2>
<p>...is the name of the Method.</p>